// import { Song } from "./interfaces/song";

// export const SONGS: Song[] = [
//     {id:1, title: 'Starman',artist:'David Bowie',id_album: 1,lyrics:"<p>Verse 1:</p><p>{D}Didn't know what time it was and the {G}lights were low</p><p>I {D}leaned back on my radio</p><p>Some {G}cat was layin' down some {A}rock 'n' roll 'lotta {D}soul,"+
//     " he said</p><br><p>Chorus:</p><p>{D}Then the loud sound did seem to fade</p><p>Came {G}back like a slow voice on a {D}wave of phase</p><p>{G}That weren't no D.J. that was {A}hazy cosmic jive</p><br><p>Verse 2:</p><p>{D}There's a starman waiting in the {G}sky</p><p>He'd {D}like to come and meet us but he thinks he'd blow our {A}minds</p><p>"+
//     "{G}There's a starman waiting in the {D}sky</p><p>He's told us not to {C}blow it 'cause he knows it's all {G}worthwhile</p><br><p>{D}He told me:</p><p>{G}Let the children lose it</p><p>{D}Let the children use it</p><p>{G}Let all the children boogie</p>",bpm:120, duration:180},
//     {id:3, title: 'Space Oddity',artist:'David Bowie',id_album: 3,lyrics:"<p>Verse 1:</p><p>{C}Ground Control to Major Tom</p><p>{C}Ground Control to Major Tom</p><p>{Am}Take your protein pills and put your helmet on</p><p>{G}Commencing countdown, engines on</p><p>{C}Ground Control to Major Tom</p><br><p>Chorus 1:</p><p>{D}Check ignition and may God's love be with you</p><br><p>Verse 2:</p><p>{C}This is Ground Control to Major Tom</p><p>You've really made the grade</p><p>{Am}And the papers want to know whose shirts you wear</p><p>{C}Now it's time to leave the capsule if you dare</p><br><p>Chorus 2:</p><p>{D}This is Major Tom to Ground Control</p><p>{D}I'm stepping through the door</p><p>{Em}And I'm floating in a most peculiar way</p><p>{Em}And the stars look very different today</p> <br><p>Verse 3:</p><p>{C}For here am I sitting in a tin can</p><p>{C}Far above the world</p><p>{Am}Planet Earth is blue and there's nothing I can do</p><p>{C}Though I'm past one hundred thousand miles</p><br><p>Chorus 3:</p><p>{D}I'm feeling very still</p><p>{D}And I think my spaceship knows which way to go</p><p>{Em}Tell my wife I love her very much she knows</p><p>{Em}Ground Control to Major Tom</p><br><p>Verse 4:</p><p>{C}Your circuit's dead, there's something wrong</p><p>{C}Can you hear me, Major Tom?</p><p>{Am}Can you hear me, Major Tom?</p><p>{C}Can you hear me, Major Tom?</p><p>{G}Can you....</p><br><p>Chorus 4:</p><p>{D}Here am I floating 'round my tin can</p><p>{D}Far above the Moon</p><p>{Em}Planet Earth is blue and there's nothing I can do</p><p>{Em}</p><p>{       D}</p>",bpm:120, duration:180},
//     {id:2, title: 'Eleanor Rigby', artist: 'The Beatles', id_album: 1, lyrics: '<p>Verse 1:</p><p>{C}Ah, look at all the lonely people</p><p>{C}Ah, look at all the lonely people</p><p>{Em}Eleanor Rigby, picks up the rice in the church where a wedding has been</p><p>{Em}Lives in a dream</p><br><p>Chorus:</p><p>{C}Waits at the window, wearing the face that she keeps in a jar by the door</p><p>{C}Who is it for?</p><br><p>Verse 2:</p><p>{C}All the lonely people, where do they all come from?</p><p>{C}All the lonely people, where do they all belong?</p><p>{Em}Father McKenzie, writing the words of a sermon that no one will hear</p><p>{Em}No one comes near</p><br><p>Chorus:</p><p>{C}Look at him working, darning his socks in the night when there\'s nobody there</p><p>{C}What does he care?</p><br><p>Bridge:</p><p>{Em}Ah, look at all the lonely people</p><p>{Em}Ah, look at all the lonely people</p><p>{C}Eleanor Rigby, died in the church and was buried along with her name</p><p>{C}Nobody came</p><br><p>{Em}Father McKenzie, wiping the dirt from his hands as he walks from the grave</p><p>{Em}No one was saved</p>', bpm: 80, duration: 125},
//     {id:4, title: 'Let\'s Dance',artist:'David Bowie',id_album: 4,lyrics:'lyrics 4',bpm:120, duration:180},
//     {id:5, title: 'BYOB',artist:'System of a Down',id_album: 5,lyrics:'lyrics 5',bpm:120, duration:180},
//     {id:6, title: 'Lonely Day',artist:'System of a Down',id_album: 6,lyrics:'lyrics 6',bpm:120, duration:180},
//     {id:7, title: 'Aerials',artist:'System of a Down',id_album: 7,lyrics:'lyrics 7',bpm:120, duration:180},
//     {id:8, title: 'Toxicity',artist:'System of a Down',id_album: 8,lyrics:'lyrics 8',bpm:120, duration:180},
//     {id:9, title: 'Chop Suey',artist:'System of a Down',id_album: 9,lyrics:'lyrics 9',bpm:120, duration:180},
//     {id:10, title: 'title 10',artist:'artist 10',id_album: 10,lyrics:'lyrics 10',bpm:120, duration:180}
// ]